<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Messenger's queue table — the durable half of ADR-0010's "send mail asynchronously".
 *
 * WHY THIS IS A MIGRATION AND NOT MESSENGER'S OWN AUTO-SETUP. The Doctrine transport will happily
 * create this table for itself the first time it is used, and `MESSENGER_TRANSPORT_DSN` carries
 * `auto_setup=0` in *every* environment — including dev — specifically to stop it. Auto-setup is a
 * schema change nobody reviewed, applied by a worker process at whatever moment it first drains a
 * queue. Worse, it makes dev and prod exercise different code paths: dev papers over a missing
 * migration with a shortcut that a locked-down production database user would not even have the
 * grants for. One reviewed file, applied by `make migrate` like everything else, is the whole point
 * of having migrations.
 *
 * WHY THIS FILE LOOKS LESS OPINIONATED THAN THE ONE BEFORE IT. `identity_email_verification_request`
 * is ours: ADR-0007 says we choose every table name, column name, physical type and index name. This
 * table is **Symfony's**, and its shape is defined by `Symfony\Component\Messenger\Bridge\Doctrine`.
 * The generated SQL is therefore kept verbatim, including two things that would be defects in a
 * table of our own:
 *
 * - the timestamps are `TIMESTAMP(0) WITHOUT TIME ZONE`, not the `WITH TIME ZONE` our own tables
 *   use. The transport writes and reads them itself in UTC and never hands them to the `Clock` port
 *   or to a Domain object, so the convention does not apply — and "correcting" it would break the
 *   transport's own comparisons.
 * - the index is called `IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750`, a Doctrine-derived hash of
 *   its columns rather than a name a human chose.
 *
 * Both are deliberate, for the same structural reason the verification table has no foreign key: the
 * schema diff is the arbiter. Doctrine compares the live database against the transport's declared
 * schema on every `make migration.make`, so a renamed index or a widened column here would be
 * diffed as drift and offered for reversal on every future run — permanent noise, forever, in
 * exchange for cosmetics on a table no application code reads. **Own your tables; do not redecorate
 * a vendor's.**
 *
 * The `failed` transport shares this table and differs only by `queue_name`, so exhausted retries
 * are moved rather than lost and no second piece of infrastructure appears to hold them.
 */
final class Version20260727211644 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Messenger: create messenger_messages for the async and failed transports (auto_setup is off on purpose).';
    }

    public function up(Schema $schema): void
    {
        // Verbatim from `make:migration` against the transport's declared schema — see the class
        // docblock for why it is not reformatted into the house style.
        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                body TEXT NOT NULL,
                headers TEXT NOT NULL,
                queue_name VARCHAR(190) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        // `(queue_name, available_at, delivered_at, id)` is precisely the worker's polling
        // predicate: pick this queue, only rows whose delay has elapsed, only rows nobody has
        // claimed, oldest first. It is the one query this table serves, run every few seconds
        // forever, which is why the transport ships an index for it rather than leaving it to
        // whoever notices the sequential scan.
        //
        // A `BIGINT GENERATED BY DEFAULT AS IDENTITY` key here is not a contradiction of ADR-0007's
        // application-assigned UUIDv7 rule: that rule is about *aggregate roots*, whose identity is
        // part of the model and must exist before the row does. A queue row is not an aggregate and
        // has no identity anyone outside this table refers to.
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750
                ON messenger_messages (queue_name, available_at, delivered_at, id)
            SQL);
    }

    public function down(Schema $schema): void
    {
        // Postgres drops the index with the table, and the identity sequence with it. Note what
        // this reversal really means: any mail still queued is discarded. That is correct for a
        // rollback — the alternative is a table of envelopes referring to a schema that no longer
        // exists — but it is a reason to drain the queue before rolling back rather than after.
        $this->addSql('DROP TABLE messenger_messages');
    }
}
